require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.1'

target 'RNFTemplate' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'RNFTemplateTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
    post_install do |installer|
      installer.pods_project.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.1'
      end
      react_native_post_install(installer)
    end
end

target 'RNFTemplate-tvOS' do
  # Pods for RNFTemplate-tvOS

  target 'RNFTemplate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
