export const assets = {
  Close: require('./Image/close.png'),
  Delete: require('./Image/delete.png'),
  Edit: require('./Image/edit.png'),
  Facebook: require('./Image/facebook.png'),
  GooglePlus: require('./Image/googlePlus.png'),
  Home: require('./Image/home.png'),
  Profile: require('./Image/profile.png'),
  Search: require('./Image/search.png'),
  Share: require('./Image/Share.png'),
  StarEmpty: require('./Image/starEmpty.png'),
  StarFilled: require('./Image/starFilled.png'),
  StarHalf: require('./Image/starHalf.png'),
  Twitter: require('./Image/twitter.png'),
};
