export const AUTH = {
  USER_LOGIN_START: 'AUTH.USER_LOGIN_START',
  USER_LOGIN_SUCCESS: 'AUTH.USER_LOGIN_SUCCESS',
  USER_LOGOUT_START: 'AUTH.USER_LOGOUT_START',
  USER_LOGOUT_SUCCESS: 'AUTH.USER_LOGOUT_SUCCESS',
};
